name: entropy_client
description: Team Enreopy - Safe Signal Client App

publish_to: 'none' # Do not remove this line

version: 0.9.263+080920  # Rule: <major>.<minor>.<commits>+<ddmmyy of last commit> <- Folowing Semantic Versioning[https://semver.org/]

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  permission_handler: ^5.0.0
  flutter_blue: ^0.7.2
  geolocator: ^5.3.2+2
  contact_picker: ^0.0.2
  shared_preferences: '>=0.5.8 <2.0.0'
  sms_maintained: ^0.2.5
  path_provider: ^1.6.11
  url_launcher: ^5.4.11
  http: ^0.12.1
  google_maps_flutter: ^0.5.27+3
  app_settings: 4.0.1+1
  fluttertoast: ^4.0.0
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.2
  package_info: ^0.4.0+16
  phone_number: ^0.6.2
  intro_slider: ^2.3.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

  # To be able to use Material Icons
  uses-material-design: true

  assets:
    - assets/googleMapsStyle.json
    - assets/loading.gif

    - i18n/en.json
    - i18n/ro.json
    - i18n/de.json

    - assets/images/robbery.png
    - assets/images/theft.png
    - assets/images/unknown.png
    - assets/images/unsafe.png
    - assets/images/violence.png
    - assets/images/all_markers.png
    - assets/images/more_bands.png
    - assets/images/how_to_pair.png
    - assets/images/how_to_test.png
